export const restaurantData = [
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
  {
    serial: 1,
    vendorName: "opu vai",
    restauranName: "Kim Jong Un",
    createdAt: "16 march 2-24",
    location: "Dhaka,bangladesh",
  },
];
