export const tableData = [
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "free",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "free",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "free",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "free",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
  {
    tableNumber: 1,
    tableName: "Table 5pair",
    seat: "5p",
    status: "booked",
  },
];
