export const transactionData = [
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
];

export const vendorRestaurantData = [
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTables: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 5000,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
  {
    serial: 1,
    name: "The New Restaurant",
    location: "Dhaka",
    totalTable: 500,
    totalMenuItems: 1000,
    status: "active",
    created: "10 march 2024",
  },
];
