export enum tagTypes {
  user = "user",
  otp = "otp",
  restaurant = "restaurant",
  menu = "menu",
  table = "table",
  booking = "booking",
  order = "order",
  notification = "notification",
  content = "content",
  wallet = "wallet",
  TopRestaurant = "TopRestaurant",
  banner = "banner",
  event = "event",
  points = "points",
  category = "category",
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.otp,
  tagTypes.restaurant,
  tagTypes.menu,
  tagTypes.table,
  tagTypes.booking,
  tagTypes.order,
  tagTypes.notification,
  tagTypes.content,
  tagTypes.wallet,
  tagTypes.TopRestaurant,
  tagTypes.banner,
  tagTypes.event,
  tagTypes.points,
  tagTypes.category,
];
